### ISSUE TITLE
Enforcing determinism / predictability for motion_bench_maker runs

### ISSUE THREAD

**Issue by RadhikaG** [KavrakiLab/motion_bench_maker#13]
Thank you for open sourcing this dataset of manipulation problems and for all the code! I was wondering, what's the best way to ensure the same plan is produced for each problem (and indeed the same series of random samples + other operations) across multiple experiment launches? 

For example, say I run `benchmark.launch` using RRTConnect for the 100 problems contained within `box_panda`, and I get a 100 different plans + a single statistics file as output. If I run `benchmark.launch` again, I'd like to get the same set of the 100 different plans and statistics as the previous `benchmark.launch` run (basically the log file output should be the same as the previous experiment).

I have tried setting the same `ompl::RNG::setSeed(seed)` before each run, but this doesn't seem to work (and I'm not sure why). Should I be using a Halton sequence as mentioned [here](https://arxiv.org/abs/2309.14545)?

(a rough outline of the solution would be sufficient, any pointers are useful!)

**Comment by ChamzasKonstantinos** [comment]
Hi @RadhikaG , I think if you determinize the sampling sequence explicitly (instead of setting the seed)  it would result into the same plans and iterations. You would get similar times,  but I don't think you can hit exactly the same planning time, as that depends on the actual CPU speed. 

To set the custom state-sampler you can see an example here (with robowflex):

https://github.com/KavrakiLab/pyre/blob/master/src/spark.cpp#L177

And here examples on how to create your own State Sampler and override the default one: 

https://github.com/KavrakiLab/pyre/blob/master/src/biased_sampler.cpp#L43
https://github.com/KavrakiLab/pyre/blob/master/src/eplanner.cpp#L71

Now to create a deterministic sampler you can use: 

The Ompl Precomputed Sampler:  https://ompl.kavrakilab.org/classompl_1_1base_1_1PrecomputedStateSampler.html
The Deterministic Halton Sampler (as you suggested) : https://ompl.kavrakilab.org/classompl_1_1base_1_1DeterministicStateSampler.html

**Comment by RadhikaG** [comment]
Thank you very much for the quick reply, and the outline of the solution!
