### ISSUE TITLE
PointCloud Data Files

### ISSUE THREAD

**Issue by elrond91** [KavrakiLab/motion_bench_maker#2]
Is there a way to get the data files of Point Cloud representation?

[pcl::PCDReader::read] Could not find file 'motion_bench_maker/problems/bookshelf_small_panda/scene_pcd0001.pcd'.

thanks!!

**Comment by ChamzasKonstantinos** [comment]
Hi @elrond91, Due to space limitations I did not store the pointclouds (since the generated files were very big). You can easily generate them if you modify the sensed_scenes.cpp script by loading the geometric scene and calling the ``octomap_generator``. 
Since there is demand for the pointclouds though I will try to generate them and upload them sometime next week. I am confident I can compress them somehow

**Comment by elrond91** [comment]
awesome!

thanks @ChamzasKonstantinos !

**Comment by ChamzasKonstantinos** [comment]
Hi @elrond91 I added the full datasets with the visualization in this [link](https://rice.box.com/s/7uwuzor40vys1xx0xec4e8mxa8fkdtnn). Let me know if there is any problem with them. I added  a simple way to visualize the pointclouds through the visualize script in this [branch](https://github.com/KavrakiLab/motion_bench_maker/tree/pcd_inclusion) which I will merge after this [PR](https://github.com/KavrakiLab/robowflex/pull/281)
